### ISSUE TITLE
Dotmesh tests aren't running due to change in CI config

### ISSUE THREAD

**Issue by itamarst** [dotmesh-io/citools#14]
A string that used to be "dotmesh-server" is now "dotmesh", and that requires corresponding change in citools or the wrong tag ("test-latest") is used for fetching images.

**Comment by prisamuel** [comment]
The reason it was changed was because the new e2e tests were expecting it to be dotmesh and not dotmesh-server. I shall put this back, and make the appropriate change in the e2e-firecracker tests.

**Comment by prisamuel** [comment]
ACK https://github.com/dotmesh-io/dotmesh/commit/ea06e424d3c0e0e4caf956afe7eaf7302e23ede4

Thanks for fixing this!
