### ISSUE TITLE
Make CI runner cleanup happen in the background

### ISSUE THREAD

**Issue by alaric-dotmesh** [dotmesh-io/citools#7]
When running in CI, it would be nice if we could report the test as finished as soon as the actual test finishes, and not have to wait for cleanup (with the risk that a timeout or error during cleanup then reports the test run as failed, when it actually passed).

### Proposed solution

Detect when we're running in CI (pick this up from an environment variable?), and if so, just touch `/dotmesh-test-pools/RUNID/finished` rather than doing the normal cleanup.

Have a cronjob that detects all RUNID directories in `/dotmesh-test-pools` that contain a `finished` or are more than a day old, and run all their cleanup actions if found (then `rm -rf` the directory, to clean up the odd empty ones we sometimes see that don't even have the delete-myself cleanup action in).

Run it... every five minutes?

**Comment by binocarlos** [comment]
Looks great! when starting a cleanup - we should drop a file (e.g. `cleaning`) to prevent the next cron job trying to delete in parallel
